.PHONY = default clean

CC = gcc
FLEX = lex
BISON = bison

default: flex bison C 
	@echo Compilation process finished

flex: recognizer.l
	@echo Compiling flex file
	@ ${FLEX} -l recognizer.l

bison: lex.yy.c parser.y
	@echo Compiling bison file
	@ ${BISON} -dv parser.y

C: lex.yy.c parser.tab.c 
	@echo Compiling c file
	@ ${CC} -o parser parser.tab.c lex.yy.c -lfl

clean:
	echo Removing autogenerated files
	@ rm -r lex.yy.c parser.tab.c parser.tab.h parser.output parser
