.PHONY = default clean

CC = gcc
FLEX = lex
BISON = bison

C_FILES = parser.tab.c lex.yy.c value.c symbol_table.c syntax_tree.c interpreter.c

run := ./parser

default: flex bison C 
	@echo Compilation process finished

flex: recognizer.l
	@echo Compiling flex file
	@ ${FLEX} -l recognizer.l

bison: lex.yy.c parser.y
	@echo Compiling bison file
	@ ${BISON} -dv parser.y

C: lex.yy.c parser.tab.c
	@echo Compiling c file
	@ ${CC} -o parser ${C_FILES} -lfl

clean:
	@echo Removing autogenerated files
	@ rm -r lex.yy.c parser.tab.c parser.tab.h parser.output parser

one: tests/one.txt
	@echo Testing one.txt
	@ ${run} tests/one.txt

two: tests/two.txt
	@echo Testing two.txt
	@ ${run} tests/two.txt

three: tests/three.txt
	@echo Testing three.txt
	@ ${run} tests/three.txt

four: tests/four.txt
	@echo Testing four.txt
	@ ${run} tests/four.txt

five: tests/five.txt
	@echo Testing five.txt
	@ ${run} tests/five.txt

six: tests/six.txt
	@echo Testing six.txt
	@ ${run} tests/six.txt

seven: tests/seven.txt
	@echo Testing seven.txt
	@ ${run} tests/seven.txt

eight: tests/eight.txt
	@echo Testing eight.txt
	@ ${run} tests/eight.txt

custom: tests/custom.txt
	@echo Testing custom.txt
	@ ${run} tests/custom.txt